language: node_js
node_js:
  - "10"

cache:
  yarn: true
  npm: true

addons:
  ssh_known_hosts: 47.75.127.82

before_install:
  - openssl aes-256-cbc -K $encrypted_4a558748f6a3_key -iv $encrypted_4a558748f6a3_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

script:
  - npm run build
  - docker build ./ -t denocn/frontend
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push denocn/frontend

after_success:
  - ssh root@47.75.127.82 "source /etc/profile;/root/denocn-frontend.sh"
