[build]
  base    = ""
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://api.denocn.org:3000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/seo/*"
  to = "http://api.denocn.org:3000/seo/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
